services:
  db:
    image: postgres:18-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  postgres-data: